### ISSUE TITLE
[Bug][Manager] Data access execution failed, resubmit exception

### ISSUE THREAD

**Issue by Greedyu** [apache/inlong#4662]
### What happened

The data access audit passed, the first time because the MQ 500 failed to execute, the exception was resubmitted after modification.

![wecom-temp-df9d646bff5e00c5a99dc4ae8da0e9e5](https://user-images.githubusercontent.com/20356765/173358425-76def0e4-22ed-4742-b6f0-cac78555ad7d.png)

```
2022-06-13 20:36:08.459 ERROR [nio-8083-exec-7] w.c.ControllerExceptionHandler:153 - failed to handle request on path: /api/inlong/manager/workflow/complete/2 by user: admin
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
        at org.apache.inlong.manager.workflow.processor.ServiceTaskProcessor.resetActionContext(ServiceTaskProcessor.java:127) ~[manager-workflow-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.workflow.processor.ServiceTaskProcessor.complete(ServiceTaskProcessor.java:103) ~[manager-workflow-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.workflow.core.impl.ProcessorExecutorImpl.executeComplete(ProcessorExecutorImpl.java:103) ~[manager-workflow-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.workflow.core.impl.TaskServiceImpl.complete(TaskServiceImpl.java:70) ~[manager-workflow-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.service.workflow.WorkflowServiceImpl.complete(WorkflowServiceImpl.java:125) ~[manager-service-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.service.workflow.WorkflowServiceImpl$$FastClassBySpringCGLIB$$cd6a46f8.invoke(<generated>) ~[manager-service-1.2.0-incubating.jar:1.2.0-incubating]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.20.jar:5.3.20]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.20.jar:5.3.20]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.18.jar:5.3.18]
        at org.apache.inlong.manager.service.workflow.WorkflowServiceImpl$$EnhancerBySpringCGLIB$$81ddf66b.complete(<generated>) ~[manager-service-1.2.0-incubating.jar:1.2.0-incubating]
        at org.apache.inlong.manager.web.controller.WorkflowController.complete(WorkflowController.java:117) ~[manager-web.jar:1.2.0-incubating]
        at org.apache.inlong.manager.web.controller.WorkflowController$$FastClassBySpringCGLIB$$e037705b.invoke(<generated>)
```

### What you expected to happen

no error

### How to reproduce

The data access approve passed, the first time because the MQ 500 failed to execute, the exception was resubmitted after modification

### Environment

centos7

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
this issue is fixed. Please use the master branch and try again.
