### ISSUE TITLE
[Bug][TubeMQ] Master start failed with NullPointerException

### ISSUE THREAD

**Issue by lucaspeng12138** [apache/inlong#5567]
### What happened

Master start failed with NullPointerException.

java.lang.NullPointerException: null
	at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:119) ~[simpleclient-0.14.1.jar:?]
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50) ~[simpleclient-0.14.1.jar:?]
	at io.prometheus.client.Collector.register(Collector.java:308) ~[simpleclient-0.14.1.jar:?]
	at io.prometheus.client.Collector.register(Collector.java:301) ~[simpleclient-0.14.1.jar:?]
	at org.apache.inlong.tubemq.server.master.stats.prometheus.MasterPromMetricService.start(MasterPromMetricService.java:52) ~[tubemq-server-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at org.apache.inlong.tubemq.server.master.TMaster.<init>(TMaster.java:219) ~[tubemq-server-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at org.apache.inlong.tubemq.server.tools.MasterStartup.main(MasterStartup.java:44) ~[tubemq-server-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]

### What you expected to happen

Master start normally.

### How to reproduce

File: inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/stats/prometheus/MasterPromMetricService.java
Caused by _start()_ function, _register()_ will use mfs which is returned from _collect()_. And when tubemq-master start, _collect()_ will return null. Then NullPointerException happens.

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lucaspeng12138** [comment]
@gosonzhang please have a check, thanks.

**Comment by gosonzhang** [comment]
@lucaspeng12138, thanks!

This is my fault, sorry, I'll deal with it right now!
