### ISSUE TITLE
[Bug][Manager] Get the inlong group failed when the Init-Sort task execution failed

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#5694]
### What happened

When the Init-Sort task execution failed, the Flink job id was not generated to the inlong group ext list.

In this scenario, query the inlong group info failed:

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/31994335/186616318-58790950-effe-47fe-bbb6-7b044479283c.png">

```
2022-08-25 11:54:07,727 -http-nio-8083-exec-9 ERROR ControllerExceptionHandler - failed to handle request on path: /inlong/manager/api/group/get/test_20220824_120 by user: admin
java.lang.NullPointerException
        at java.util.HashMap.merge(HashMap.java:1226)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.apache.inlong.manager.service.group.InlongGroupServiceImpl.buildSortConfig(InlongGroupServiceImpl.java:424)
        at org.apache.inlong.manager.service.group.InlongGroupServiceImpl.get(InlongGroupServiceImpl.java:176)
        at org.apache.inlong.manager.service.group.InlongGroupServiceImpl$$FastClassBySpringCGLIB$$b1589cb7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at org.apache.inlong.manager.service.group.InlongGroupServiceImpl$$EnhancerBySpringCGLIB$$3f42e525.get(<generated>)
        at org.apache.inlong.manager.web.controller.InlongGroupController.get(InlongGroupController.java:74)
        at org.apache.inlong.manager.web.controller.InlongGroupController$$FastClassBySpringCGLIB$$c753fc7a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```
### What you expected to happen

The group information of initsort failure can be viewed normally

### How to reproduce

Create a new group information, and then click query group information after initsort fails.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problem.
