### ISSUE TITLE
[Bug][Manager] Workflow initialization threw NPE exception when esVersion attribute is null.

### ISSUE THREAD

**Issue by wangpeix** [apache/inlong#6805]
### What happened

Workflow initialization threw NPE exception when esVersion attribute is null.

### What you expected to happen

```java
java.lang.NullPointerException: null
        at org.apache.inlong.manager.pojo.sort.util.LoadNodeUtils.createLoadNode(LoadNodeUtils.java:447) ~[manager-pojo-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.pojo.sort.util.LoadNodeUtils.createLoadNode(LoadNodeUtils.java:130) ~[manager-pojo-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.pojo.sort.util.LoadNodeUtils.lambda$createLoadNodes$0(LoadNodeUtils.java:99) ~[manager-pojo-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
        at org.apache.inlong.manager.pojo.sort.util.LoadNodeUtils.createLoadNodes(LoadNodeUtils.java:100) ~[manager-pojo-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.service.resource.sort.DefaultSortConfigOperator.createNodes(DefaultSortConfigOperator.java:204) ~[manager-service-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.service.resource.sort.DefaultSortConfigOperator.getGroupInfo(DefaultSortConfigOperator.java:143) ~[manager-service-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.service.resource.sort.DefaultSortConfigOperator.buildConfig(DefaultSortConfigOperator.java:88) ~[manager-service-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
        at org.apache.inlong.manager.service.listener.sort.SortConfigListener.listen(SortConfigListener.java:101) ~[manager-service-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
```

### How to reproduce

Configure writing to es on the dashboard. Then, this problem will occur during initialization.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangpeix** [comment]
This problem has been solved in #6837.  It can be closed.
