### ISSUE TITLE
[Bug][Sort] Fix issue of tableidentifier being null when addRow

### ISSUE THREAD

**Issue by Yizhou-Yang** [apache/inlong#7286]
### What happened

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.inlong.sort.doris.table.DorisDynamicSchemaOutputFormat.load(DorisDynamicSchemaOutputFormat.java:742) ~[pool-1-thread-5-1675066174508-test-sort-connector-doris-1.5.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.inlong.sort.doris.table.DorisDynamicSchemaOutputFormat.flushSingleTable(DorisDynamicSchemaOutputFormat.java:669) ~[pool-1-thread-5-1675066174508-test-sort-connector-doris-1.5.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.inlong.sort.doris.table.DorisDynamicSchemaOutputFormat.flush(DorisDynamicSchemaOutputFormat.java:646) ~[pool-1-thread-5-1675066174508-test-sort-connector-doris-1.5.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at org.apache.inlong.sort.doris.table.DorisDynamicSchemaOutputFormat.lambda$open$1(DorisDynamicSchemaOutputFormat.java:298) ~[pool-1-thread-5-1675066174508-test-sort-connector-doris-1.5.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]

### What you expected to happen

successfully run task

### How to reproduce

doris multiple sink archive

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by #7287
